### ISSUE TITLE
Fail to Load

### ISSUE THREAD

**Issue by nubt** [EasyFarm/EasyFarm#226] opened 2016-11-15 06:16 UTC
I can't save or load routes and sometimes my settings

**Comment by Mykezero** [comment] 2016-12-18 21:36
@nubt  That doesn't sound good. Have you tried the newest version of the program?

Also, does the program crash when attempting to save the settings and routes?

**Comment by nubt** [comment] 2016-12-19 18:16
New version works fine so far.  It wouldn't crash or anything.  Just said failed to save/load settings or paths whenever I tried to making me redo everything when ever I ran it.

**Comment by Mercurian** [comment] 2016-12-21 07:42
Gotta bump this, yeah, settings won't save. Not really a big deal, but it's an annoyance.

They SAVE, but if you close and open then try to load it will fail.

**Comment by nubt** [comment] 2016-12-28 23:58
yeah i'm getting the same load/save fails again after dl'ing v93

**Comment by Mykezero** [comment] 2016-12-31 23:15
For some reason, I can't seem to replicate this. Could someone share a screen shot of the settings? You can paste the picture in the comment box.

**Comment by Mercurian** [comment] 2017-01-01 17:17
I tried to drag and drop some pix to help replicate, but the website tells me I can't u_u;;

It's pretty easy to replicate, set up the program: run a route, set voke(or any JA) set a ws, then save (it will save) close it, and re-open, try to load (it will fail to load).

But you have to set a minimum number of things ( i dont know how many) to cause it to fail to load.

**Comment by Mykezero** [comment] 2017-01-01 21:31
Thanks @Mercurian ! This should definitely help with figuring out what's going on!!

**Comment by nubt** [comment] 2017-01-02 23:22
![image](https://cloud.githubusercontent.com/assets/23470308/21597388/60689cd4-d0ee-11e6-9aaf-4b65cc14ea3f.png)

**Comment by nubt** [comment] 2017-01-02 23:25
above path was just a wavy line from one end of an escha ruan platform to the other

**Comment by Mykezero** [comment] 2017-01-08 19:37
@Mercurian @nubt Would you mind downloading the newest version of the program and try loading those settings again? I've added extra logging to the application, and adjusted it so that it will log those errors to the Logs/easyfarm.log file. That log file should now contain the reason why the settings are failing to load.

**Comment by Mercurian** [comment] 2017-01-08 19:44
Failed to load:

2017-01-08 14:43:08.8698|INFO|LogSink|EasyFarm Started ...
2017-01-08 14:43:46.7950|ERROR|LogSink|EasyFarm.Classes.SettingsManager.TrySave : Failure on de-serialize settings
System.InvalidOperationException: There is an error in XML document (283, 23). ---> System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not closed: H, Position, Waypoints, Route, Config. Line 283, position 23.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ThrowUnclosedElements()
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.ReadString()
   at System.Xml.XmlTextReader.ReadString()
   at System.Xml.XmlReader.ReadElementString()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read11_Position(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read13_Route(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read14_Config(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read15_Config()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at EasyFarm.Classes.Serialization.Deserialize[T](String filename) in C:\projects\easyfarm\EasyFarm\Classes\Serialization.cs:line 64
   at EasyFarm.Classes.SettingsManager.TryLoad[T]() in C:\projects\easyfarm\EasyFarm\Classes\SettingsManager.cs:line 88

**Comment by Mercurian** [comment] 2017-01-08 19:47
Secondary failure to load: Different settings etc

2017-01-08 14:47:05.1333|ERROR|LogSink|EasyFarm.Classes.SettingsManager.TrySave : Failure on de-serialize settings
System.InvalidOperationException: There is an error in XML document (281, 2). ---> System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not closed: Position, Waypoints, Route, Config. Line 281, position 2.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ThrowUnclosedElements()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.ReadStartElement()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read11_Position(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read13_Route(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read14_Config(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read15_Config()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at EasyFarm.Classes.Serialization.Deserialize[T](String filename) in C:\projects\easyfarm\EasyFarm\Classes\Serialization.cs:line 64
   at EasyFarm.Classes.SettingsManager.TryLoad[T]() in C:\projects\easyfarm\EasyFarm\Classes\SettingsManager.cs:line 88

**Comment by Mercurian** [comment] 2017-01-08 20:16
Another one, different line error

2017-01-08 15:15:43.0996|INFO|LogSink|EasyFarm Started ...
2017-01-08 15:15:55.3783|ERROR|LogSink|EasyFarm.Classes.SettingsManager.TrySave : Failure on de-serialize settings
System.InvalidOperationException: There is an error in XML document (302, 40). ---> System.Xml.XmlException: Unexpected end of file while parsing Name has occurred. Line 302, position 40.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.ReadString()
   at System.Xml.XmlTextReader.ReadString()
   at System.Xml.XmlReader.ReadElementString()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read14_Config(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read15_Config()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at EasyFarm.Classes.Serialization.Deserialize[T](String filename) in C:\projects\easyfarm\EasyFarm\Classes\Serialization.cs:line 64
   at EasyFarm.Classes.SettingsManager.TryLoad[T]() in C:\projects\easyfarm\EasyFarm\Classes\SettingsManager.cs:line 88

**Comment by Mykezero** [comment] 2017-01-08 21:41
@Mercurian Those were three different config files

> System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not closed: H, Position, Waypoints, Route, Config. Line 283, position 23.

It seems to create the file, but when it's writing it to disk, it isn't doing it correctly. So when the file is finally saved, it won't be able to load it correctly.

My guess would be that the problem is the Route class which was recently created: it may contain something that the file-saver cannot save. 

Thanks for share the logs files!

**Comment by nubt** [comment] 2017-01-10 01:45
2017-01-08 23:00:15.6802|INFO|LogSink|EasyFarm Started ...
2017-01-08 23:08:37.1804|ERROR|LogSink|EasyFarm.Classes.SettingsManager.TrySave : Failure on de-serialize settings
System.InvalidOperationException: There is an error in XML document (319, 9). ---> System.Xml.XmlException: Unexpected end of file while parsing Name has occurred. Line 319, position 9.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.ReadElementString()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderRoute.Read2_Position(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderRoute.Read4_Route(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderRoute.Read5_Route()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at EasyFarm.Classes.Serialization.Deserialize[T](String filename) in C:\projects\easyfarm\EasyFarm\Classes\Serialization.cs:line 64
   at EasyFarm.Classes.SettingsManager.TryLoad[T]() in C:\projects\easyfarm\EasyFarm\Classes\SettingsManager.cs:line 88

**Comment by nubt** [comment] 2017-01-10 01:46
2017-01-08 22:49:23.3596|INFO|LogSink|EasyFarm Started ...
2017-01-08 22:59:08.8293|ERROR|LogSink|EasyFarm.Classes.SettingsManager.TrySave : Failure on serialize settings
System.InvalidOperationException: There was an error generating the XML document. ---> System.InvalidOperationException: Instance validation error: '289' is not a valid value for MemoryAPI.Zone.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterRoute.Write3_Zone(Zone v)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterRoute.Write4_Route(String n, String ns, Route o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterRoute.Write5_Route(Object o)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at System.Xml.Serialization.XmlSerializer.Serialize(Stream stream, Object o, XmlSerializerNamespaces namespaces)
   at EasyFarm.Classes.Serialization.Serialize[T](String filename, T value) in C:\projects\easyfarm\EasyFarm\Classes\Serialization.cs:line 45
   at EasyFarm.Classes.SettingsManager.TrySave[T](T value) in C:\projects\easyfarm\EasyFarm\Classes\SettingsManager.cs:line 60

**Comment by Mykezero** [comment] 2017-01-10 02:38
@nubt Thanks for the extra information! That last one seems to have blown up on converting the zone id to something in the program

> System.InvalidOperationException: Instance validation error: '289' is not a valid value for MemoryAPI.Zone.

It appears that zone 289 is not defined in the program, so it cannot properly map it back to value. Great find!

**Comment by nubt** [comment] 2017-01-13 05:19
my settings were loading fine til i got this;

2017-01-12 19:16:33.8374|INFO|LogSink|EasyFarm Started ...
2017-01-12 19:17:07.7750|ERROR|LogSink|EasyFarm.Classes.SettingsManager.TrySave : Failure on de-serialize settings
System.InvalidOperationException: There is an error in XML document (1148, 4). ---> System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not closed: Position, Waypoints, Route, Config. Line 1148, position 4.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ThrowUnclosedElements()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.ReadElementString()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read11_Position(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read13_Route(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read14_Config(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read15_Config()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at EasyFarm.Classes.Serialization.Deserialize[T](String filename) in C:\projects\easyfarm\EasyFarm\Classes\Serialization.cs:line 64
   at EasyFarm.Classes.SettingsManager.TryLoad[T]() in C:\projects\easyfarm\EasyFarm\Classes\SettingsManager.cs:line 88

**Comment by nubt** [comment] 2017-01-20 22:15
another setting load fail:

2017-01-19 23:26:35.1046|INFO|LogSink|EasyFarm Started ...
2017-01-19 23:27:01.0990|ERROR|LogSink|EasyFarm.Classes.SettingsManager.TrySave : Failure on de-serialize settings
System.InvalidOperationException: There is an error in XML document (750, 3). ---> System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not closed: Position, Waypoints, Route, Config. Line 750, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ThrowUnclosedElements()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.ReadElementString()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read11_Position(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read13_Route(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read14_Config(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfig.Read15_Config()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at EasyFarm.Classes.Serialization.Deserialize[T](String filename) in C:\projects\easyfarm\EasyFarm\Classes\Serialization.cs:line 64
   at EasyFarm.Classes.SettingsManager.TryLoad[T]() in C:\projects\easyfarm\EasyFarm\Classes\SettingsManager.cs:line 88

**Comment by Mykezero** [comment] 2017-01-23 00:24
**Important!: Make sure you keep a back up of your existing settings files before trying the newest version.** 

I've pushed a new update out that uses a different library for saving settings. You should be able to load the old settings files, but when you save them, it will convert them into the new format. Sadly, for the already non-working settings, the program will not be able to load them.

**Comment by Mykezero** [comment] 2017-02-25 22:27
Did this fix the problem?

**Closed by Mykezero** 2017-02-25 22:27 UTC
Labels: bug

**Comment by Mercurian** [comment] 2017-03-08 11:33
I'll be totally honest here, I only update the easy farm when the game breaks the current one.

So I currently have no idea if the issue is fixed or not, I'm still using .98 until the next update breaks it, I just saved the profile with no route, and rerun the short route whenever I turn off the pc for now.
