### ISSUE TITLE
Old issue is back .103

### ISSUE THREAD

**Issue by Mercurian** [EasyFarm/EasyFarm#248] opened 2017-04-07 22:38 UTC
Having that same old issue I talked about before.

Mob in wander range, targeted, moves out of range, aggro, targeting conflict resulting in death.

With and without tab targeting.

It was working well with .101 I really have no idea why it's happening again. 

Oh damn I may have just seen it happen. It's the priority targeting. I was aggrod by a mob, but tabbed to a MUCH further away mob, while the game was trying to attack the aggro, the bot was trying to retarget.

Yup, just watched it happen twice, tab targeting is not working well at all

( i never used tab targeting before, but since the old wander issue came back, i tried it, definitely can't use tab targeting at all)

**Comment by Crysez** [comment] 2017-04-09 17:06
I havent experienced anything like this with the normal targeting method (no tab-target).  

Probably not the solution you are looking for - but this things runs smoothly for like 24+hrs straight without tab target.

**Comment by Mercurian** [comment] 2017-04-10 04:11
In the particular camp I chose, it is an issue (with and without tab).

The surrounding area is fucking terrible with obstructions. If I turn wander on too high, I'll get stuck behind a wall. (the wiggle mechanic isn't sufficient to avoid).

What happens is targetting priority. If a mob aggros you and you attack a different mob at the same time, the game itself locks onto one, but targets the other. it's fucked up. 99.99% of the time it works perfectly fine. But at least once per day it happens. 

When it happens I die. There's absolutely nothing that can be adjusted to change it, trusts can't heal, you can't do damage. You just stand there like a statue.

**Comment by Crysez** [comment] 2017-04-10 04:29
Oh, i remember this issue.  You are describing the same thing I did back when i posted about it.  

I thought it was fixed.  But I left the zitah camp (which i guess is where you are), so I didnt realize it still persisted.  

Would recommend moving to ruaun or reisenjima.

**Comment by Mercurian** [comment] 2017-04-10 04:31
While I don't want to advertise where or what etc, its not zitah. 

But the problem lies within how aggro is prioritized. There have been a lot of times I'd have 3 or 4 mobs attacking, while still running to the next "way point" in route, then sometimes targeting a new mob, while the 3 are still attacking.

That's why I worry about adding a box opener.

**Comment by Crysez** [comment] 2017-04-10 04:34
Odd.  I am in a cap with no agro, but plenty of linking.  The linked obs dont have this issue at all.  

It always kills the links before moving to a new mob.  

I havent experienced anything like this since changing camps

**Comment by Mercurian** [comment] 2017-04-10 04:36
Right this second, i have 3 mobs attacking me: 

I'll kill one, run to a way point, attack another, kill, run to a way point, every time I run to a new waypoint, i pick up more aggro. Sometimes in that moment when the way point is hit, an unaggro mob my become the new target.

**Comment by Crysez** [comment] 2017-04-10 04:38
Ah, i guess its because it already started back to the waypoint.  For me, it kills all the adds before heading to waypoint (theres no agro mobs here).  

I suppose the issue is that once it starts heading back to a waypoint it stops checking for agro(?)

**Comment by Mercurian** [comment] 2017-04-10 04:41
I'm really not smart enough to make that call, I just know what I see. 

When there's no aggro, it works perfect. 

When there's a single waypoint (like you'd use in rakaz in the middle of butterflies) it's perfect.

When you run a route and have aggro, this targeting issue happens (albeit very rarely) it is noticeable.

**Comment by Crysez** [comment] 2017-04-10 04:46
Well, sounds like you know how to isolate it.  

I just really wanna know where you are camping now, you tease.
I bet you found something really juicy & dont want to share ;_;

**Comment by Mercurian** [comment] 2017-04-10 04:49
It's just a high profit camp. Think of what mobs would make you a lot of gil. 

Example: what mob drops a very valuable NPC item/Ah item? Then farm the hell out of it.

**Comment by Crysez** [comment] 2017-04-10 04:50
I've already done that exercise.  I found what I think is a great spot, but I know there are better out there :p

**Comment by Mercurian** [comment] 2017-04-10 04:55
So this is way off topic, but when I started I was doing the Rakaz thing, cause 100% dark weather means a LOT of shadow geodes and fenrites (goldsmithing main etc) good profit camp until everyone found out about it, now there are people there all day every. sad. 

Crabs in adoulin are also a high profit camp, HQ shells are like 100k. + meats + nq shells + near constant water weather. Either one of those would net like 10m a day.

**Comment by Crysez** [comment] 2017-04-10 05:03
Never looked at the crabs.  I bet it was good back when leviatites were worth something

**Comment by Crysez** [comment] 2017-04-22 22:06
Have you noticed your character warping to waypoints occasionally?  Seems to happen to me once every few minutes, and he's sometimes jumping like 10-15yalms.  

Trying to figure out why this is happening and if I screwed something up in the settings?  

Extra noticeable when I have gravity on me.

**Comment by Mercurian** [comment] 2017-04-23 00:41
Yes... it's been kinda poshacking... "jumping" around on pathing.

**Comment by Crysez** [comment] 2017-04-23 01:53
Only since the last update, yea?  Was it to avoid getting stuck?

Seems to happen all the time when not stuck

**Comment by Crysez** [comment] 2017-04-23 15:14
Update: totally worth it.  I am in a new spot with a long path, lots of shit in the way.  

Just saw myself get 'permanently' stuck, but it got out of it using pos

**Comment by Crysez** [comment] 2017-04-23 16:54
Another update:  jumped off a cliff and got stuck underground :(

Need a new camp i guess

**Comment by Mykezero** [comment] 2017-04-23 20:20
I changed the program to use the new auto follow feature in the elite api; that might be causing the weird pathing issues. The program should definitely not allow the player to be warping around.

**Comment by Mercurian** [comment] 2017-04-23 20:24
It's not like "warping" around. how can I describe it.

Its like it'll be running along, and then JUMP forward. Like a speed boost. Like a car with a trans problem it leaps forward (and backwards sometimes!).

Like you're running at 18% speed, then run at flee speed for one quick moment, then back to normal. It could accelerate you past your waypoints on the path. which may be what happened to him.

**Comment by Crysez** [comment] 2017-04-23 20:28
Oh, its definitely using pos hack.  I thought it was intentional.  

Its pretty obvious.  Just run the bot along a path for 5min and you will see your character jump around a bunch.  Honestly, its pretty useful for when you get stuck on a wall.  Its also only over very short distances.

My toon also jump on the z axis to get over walls/hills when he gets stuck.  This part is very useful.  

The part i dont like is what mercurian described.  The X & Y axis jumps.  Its seems to happen completely randomly.  I believe it is actually pos hack (not speed boost), because my char has jumped off the same cliff twice today by jumping on X axis

**Comment by Mykezero** [comment] 2017-04-23 21:57
I've removed the auto follow code for now since I'd hate leaving something very dangerous like that laying around. The good news is it looks like the work for smoothing out the path navigation code is still working very nicely ^^;

**Closed** 2018-04-08 19:15 UTC
Labels: bug
